# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitcollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='download_bytes_now_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='download_bytes_total_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='download_errors_now_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='download_errors_total_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='download_packets_now_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='download_packets_total_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='upload_bytes_now_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='upload_bytes_total_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='upload_errors_now_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='upload_errors_total_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='upload_packets_now_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='upload_packets_total_last',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='download_bytes_now',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='download_bytes_total',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='download_errors_now',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='download_errors_total',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='download_packets_now',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='download_packets_total',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='upload_bytes_now',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='upload_bytes_total',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='upload_errors_now',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='upload_errors_total',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='upload_packets_now',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='upload_packets_total',
            field=models.TextField(null=True),
        ),
    ]
