#!/bin/sh

function evaluate_result(){
  local returnvalue="${1}"
  local message="${2}"
  if [ "$returnvalue" -eq 0 ]; then
    echo -e "\e[32m  [PASS] ${message}\e[0m"
  else
    echo -e "\e[31m  [FAIL] ${message}\e[0m"
    exit 1
  fi
}

function waiting() {
  local seconds="${1}"
  local message="${2}"
  echo -e "\e[33m  [...] Waiting ${seconds}s ${message}\e[0m"
  sleep ${seconds}
}

function info() {
  local message="${1}"
  echo -e "\e[36m  [INFO]  ${message}\e[0m"
}

function arch() {
  case $(uname -m) in
    amd64|x86_64) ARCH="amd64" && return 0;;
    armv*|armhf) ARCH="arm" && return 0;;
    aarch64|amd64) ARCH="aarch64" && return 0;;
    *) ARCH=" Unsupported Architecture" && return 1;;
  esac
}

function check_dependencies() {
   command -v "docker" >/dev/null 2>&1
   evaluate_result $? " Docker is installed"
   command -v "docker-compose" >/dev/null 2>&1
   evaluate_result $? " Docker-compose is installed"
}
