#!/bin/sh

function arch() {
  case $(uname -m) in
    x86_64) ARCH="amd64";;
    armv7l|armv6l) ARCH="armhf";;
    *) echo "Unsupported Architecture" && exit 0;;
  esac
  echo "Detected architecture: ${ARCH}"
}
