#!/bin/sh

ALPINE_64="alpine:3.4"
PYTHON_64="python:3.5-alpine"
ALPINE_ARM="armhf/alpine:3.4"
PYTHON_ARM="armhf/python:3.5-alpine"

function alpine_dockerfile() {
  local generic="${3:-$PWD}/${1}"
  local output="${3:-$PWD}/${2}"
  if [ "${ARCH}" == "amd64" ]; then
    sed -e "s/<IMAGE>/${ALPINE_64}/g" -e "s/<ARCH>/${ARCH}/g" "${generic}" > ${output}
    return 0
  elif [ "${ARCH}" == "armhf" ]; then
    sed -e "s/<IMAGE>/${ALPINE_ARM}/g" -e "s/<ARCH>/${ARCH}/g" "${generic}" > ${output}
    return 0
  else
    return 1
  fi
}

function python_dockerfile() {
  local generic="${3:-$PWD}/${1}"
  local output="${3:-$PWD}/${2}"
  if [ "${ARCH}" == "amd64" ]; then
    sed -e "s/<IMAGE>/${PYTHON_64}/g" -e "s/<ARCH>/${ARCH}/g" "${generic}" > ${output}
    return 0
  elif [ "$ARCH" == "armhf" ]; then
    sed -e "s/<IMAGE>/${PYTHON_ARM}/g" -e "s/<ARCH>/${ARCH}/g" "${generic}" > ${output}
    return 0
  else
    return 1
  fi
}
